server:
  port: 8081
  
spring:
  application:
    name: Person-App
  datasource:
#for h2 database
    #url: jdbc:h2:~/test
    #username: sa
    #password: password
    #driverClassName: org.h2.Driver
    
#for Mysql database
    url: jdbc:mysql://localhost:3306/person
    username: root
    password: root
    
#jpa properties
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    
      